// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtewjjalrpnwdcnoxbvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0ZXdqamFscnBud2Rjbm94YnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzY3MDYsImV4cCI6MjA2NjkxMjcwNn0.vZU2ngKVjZgY5-Gcu4JibHHczwYua8BbmBXWzxsv3ME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});